services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000" # blob
    volumes:
      - ./azurite:/data
    environment:
      AZURITE_ACCOUNTS: "devstoreaccount1:Eby8vdM02xNOcqFEYpYJys2OV8I6r9Q1qho="
    command: "azurite --blobHost 0.0.0.0 --location /data"

  spark:
    image: apache/spark-py
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    command: [ "/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "spark", "--port", "7077", "--webui-port", "8080" ]
